import {styles,layouts,fields,defaults,clean,sizeLabel,generate} from './engine.mjs';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];const DRAFT='poster-studio-draft-v1',SAVED='poster-studio-presets-v1';let state={...defaults},manual=false,presets=[],timer;
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function storeDraft(){try{localStorage.setItem(DRAFT,JSON.stringify({data:state,prompt:$('#prompt').value,manual}));$('#saveState').textContent='● 草稿已自動儲存';}catch{$('#saveState').textContent='草稿未儲存，請匯出備份';}}
try{const v=JSON.parse(localStorage.getItem(DRAFT));if(v){state=clean(v.data);manual=v.manual===true&&typeof v.prompt==='string';if(manual)$('#prompt').value=v.prompt.slice(0,50000);}const p=JSON.parse(localStorage.getItem(SAVED));if(Array.isArray(p))presets=p.filter(x=>x&&typeof x.id==='string'&&typeof x.name==='string'&&x.data).map(x=>({...x,data:clean(x.data)}));}catch{}
function setTab(t){if(state.mode==='edit'&&t!=='content')return;$$('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===t);b.setAttribute('aria-current',b.dataset.tab===t?'step':'false');});$$('.panel').forEach(p=>p.hidden=p.id!=='panel-'+t);}
function syncForm(){for(const k in defaults){const el=$(`#form [name="${k}"]`);if(el){if(el.type==='checkbox')el.checked=state[k];else el.value=state[k];}}}
function render(){const edit=state.mode==='edit';$$('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===state.mode);b.setAttribute('aria-pressed',b.dataset.mode===state.mode);});$('#modeHelp').textContent=edit?'只描述指定的修改項目，使用時請另外附上原始海報。':state.mode==='background'?'適合文案較多的海報：生成乾淨底圖，之後再加入精確文字。':'將文案與圖像一起生成，完成後請核對文字、日期與電話。';$('#editFields').hidden=!edit;$('#titleRequired').hidden=edit;$$('[data-tab]').forEach(b=>b.disabled=edit&&b.dataset.tab!=='content');$$('[data-go]').forEach(b=>b.hidden=edit);$('#sizeTag').textContent=edit?'沿用原圖':state.size==='square'?'1:1 正方形':state.size==='story'?'9:16 直式':`${state.size} ${state.orientation==='portrait'?'直式':'橫式'}`;$('.preview-stage').hidden=edit;$('.preview-caption').textContent=edit?'修改模式保留原圖構圖，不另套用風格與排版設定。':'僅為區塊與配色示意，不是 AI 生成海報';$('#form [name=orientation]').disabled=['square','story'].includes(state.size);$('#mainHex').textContent=state.main.toUpperCase();$('#accentHex').textContent=state.accent.toUpperCase();$$('[data-style]').forEach(b=>{b.classList.toggle('active',b.dataset.style===state.style);b.setAttribute('aria-pressed',b.dataset.style===state.style);});$$('[data-layout]').forEach(b=>{b.classList.toggle('active',b.dataset.layout===state.layout);b.setAttribute('aria-pressed',b.dataset.layout===state.layout);});const p=$('#poster');p.style.setProperty('--main',state.main);p.style.setProperty('--accent',state.accent);p.className='poster '+state.layout;let ratio=state.size==='square'?1:state.size==='story'?9/16:state.orientation==='portrait'?1/Math.SQRT2:Math.SQRT2;let h=250,w=h*ratio;if(w>320){w=320;h=w/ratio;}p.style.width=w+'px';p.style.height=h+'px';$('#posterTitle').textContent=state.title.trim()||'把靈感\n留在這裡';$('#posterSubtitle').textContent=state.subtitle.trim()||'為下一張好海報，留一點想像。';$('#posterInfo').textContent=state.mode==='background'?'課程資訊預留區':state.date.trim()||'課程資訊';$('#logoSlot').hidden=!state.logo;$('#qrSlot').hidden=!state.qr;if(!manual)$('#prompt').value=generate(state);$('#manualNotice').hidden=!manual;$('#charCount').textContent=Array.from($('#prompt').value).length+' 字';$('#savedCount').textContent=presets.length;storeDraft();}
for(const [key,s]of Object.entries(styles)){const b=document.createElement('button');b.type='button';b.dataset.style=key;b.className='style-card';const sw=document.createElement('div');sw.className='style-swatch';sw.style.background=s.accent;sw.style.color=s.main;const txt=document.createElement('span');txt.textContent='DESIGN / '+String(Object.keys(styles).indexOf(key)+1).padStart(2,'0');sw.append(txt);const label=document.createElement('strong');label.textContent=s.name;b.append(sw,label);$('#styleCards').append(b);}
for(const [key,l]of Object.entries(layouts)){const b=document.createElement('button');b.type='button';b.dataset.layout=key;b.className='layout-card';b.innerHTML=`<div class="mini-layout ${key}"><i></i><i></i><i></i></div>`;b.append(document.createTextNode(l.name));$('#layoutCards').append(b);}
$('#form').addEventListener('submit',e=>e.preventDefault());$('#form').addEventListener('input',e=>{const k=e.target.name;if(k in defaults){state[k]=e.target.type==='checkbox'?e.target.checked:e.target.value;render();}});$$('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;if(state.mode==='edit')setTab('content');render();});$$('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$$('[data-go]').forEach(b=>b.onclick=()=>{setTab(b.dataset.go);$('.tabs').scrollIntoView({block:'start',behavior:'smooth'});});$$('[data-style]').forEach(b=>b.onclick=()=>{const k=b.dataset.style;Object.assign(state,{style:k,main:styles[k].main,accent:styles[k].accent});syncForm();render();});$$('[data-layout]').forEach(b=>b.onclick=()=>{state.layout=b.dataset.layout;render();});$('#prompt').oninput=()=>{manual=true;$('#manualNotice').hidden=false;$('#charCount').textContent=Array.from($('#prompt').value).length+' 字';storeDraft();};$('#regenerate').onclick=()=>{if(manual&&!confirm('重新產生會取代你手動修改的提示詞，確定繼續？'))return;manual=false;render();toast('已依目前設定重新產生');};
function validate(){if(!$('#prompt').value.trim()){toast('提示詞目前是空白');return false;}if(manual)return true;const key=state.mode==='edit'?'changes':'title';if(!state[key].trim()){setTab('content');$(`[name=${key}]`).focus();toast(state.mode==='edit'?'請先填寫要修改的內容':'請先填寫課程／活動名稱');return false;}return true;}
$('#copy').onclick=async()=>{if(!validate())return;try{await navigator.clipboard.writeText($('#prompt').value);toast('已複製，可以貼到圖片生成工具了');}catch{$('#prompt').focus();$('#prompt').select();let ok=false;try{ok=document.execCommand('copy');}catch{}toast(ok?'已複製提示詞':'請按 Ctrl+C（Mac：⌘C）複製已選取的文字');}};
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
$('#downloadText').onclick=()=>{if(validate())download($('#prompt').value,'海報提示詞.txt','text/plain;charset=utf-8');};
$('#sample').onclick=()=>{if((state.title||state.changes||manual)&&!confirm('載入範例將取代目前草稿，確定繼續？'))return;state={...defaults,title:'一級美甲師檢定衝刺班',subtitle:'一次考兩張證照，提升現場美甲師實力',details:'凝膠彩繪技巧\n檢定實作練習\n作品細節指導'};manual=false;syncForm();setTab('content');render();toast('已載入範例；日期、地點與費用請自行填寫');};$('#reset').onclick=()=>{if(!confirm('清空目前草稿並恢復預設？已儲存的設定會保留。'))return;state={...defaults};manual=false;syncForm();setTab('content');render();toast('已恢復預設');};
function savePresets(next){try{localStorage.setItem(SAVED,JSON.stringify(next));presets=next;$('#savedCount').textContent=presets.length;return true;}catch{toast('無法儲存，請使用匯出設定檔備份');return false;}}
function renderSaved(){$('#savedList').replaceChildren();if(!presets.length){const p=document.createElement('p');p.className='empty';p.textContent='還沒有儲存設定，先留下你的第一個設計。';$('#savedList').append(p);}for(const item of presets){const row=document.createElement('div');row.className='saved-row';const name=document.createElement('div');name.className='saved-name';name.textContent=item.name;const small=document.createElement('small');const dt=new Date(item.time);small.textContent=Number.isNaN(+dt)?'已存設定':dt.toLocaleString('zh-TW');name.append(small);const load=document.createElement('button');load.textContent='載入';load.onclick=()=>{if(!confirm('載入此設定並取代目前草稿？'))return;state=clean(item.data);manual=typeof item.prompt==='string'&&item.manual===true;if(manual)$('#prompt').value=item.prompt.slice(0,50000);syncForm();setTab('content');render();$('#savedDialog').close();toast('已載入「'+item.name+'」');};const del=document.createElement('button');del.textContent='刪除';del.setAttribute('aria-label','刪除 '+item.name);del.onclick=()=>{if(confirm('刪除「'+item.name+'」？')&&savePresets(presets.filter(p=>p.id!==item.id)))renderSaved();};row.append(name,load,del);$('#savedList').append(row);}}
function showSaved(focus){$('#presetName').value=state.title||'';renderSaved();$('#savedDialog').showModal();if(focus)$('#presetName').focus();}$('#openSaved').onclick=()=>showSaved(false);$('#savePreset').onclick=()=>showSaved(true);$('#closeSaved').onclick=()=>$('#savedDialog').close();$('#confirmSave').onclick=()=>{const name=$('#presetName').value.trim();if(!name){$('#presetName').focus();toast('請輸入設定名稱');return;}if(savePresets([...presets,{id:crypto.randomUUID(),name,time:new Date().toISOString(),data:{...state},manual,prompt:$('#prompt').value}])){renderSaved();toast('設定已儲存');}};$('#export').onclick=()=>download(JSON.stringify({app:'poster-prompt-studio',version:1,data:state,manual,prompt:$('#prompt').value},null,2),'海報提示詞設定.json','application/json');$('#import').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>200000)throw Error();const obj=JSON.parse(await f.text());if(obj.app!=='poster-prompt-studio'||obj.version!==1||!obj.data||typeof obj.data!=='object')throw Error();if(!confirm('匯入設定將取代目前草稿，確定繼續？'))return;state=clean(obj.data);manual=obj.manual===true&&typeof obj.prompt==='string';if(manual)$('#prompt').value=obj.prompt.slice(0,50000);syncForm();setTab('content');render();$('#savedDialog').close();toast('已匯入設定');}catch{toast('無法讀取，請選擇本工具匯出的 JSON 設定檔');}finally{e.target.value='';}};
syncForm();render();
