export const styles = {
 elegant:{name:'優雅美甲',desc:'柔和、細緻、留白充足，呈現美甲作品的質感；少量弧線與柔光點綴',main:'#A18ABC',accent:'#F3EAF3'},
 salon:{name:'專業美髮',desc:'現代沙龍編輯風格，俐落字級層次，剪刀、梳子或髮絲元素作少量點綴',main:'#425C54',accent:'#E8EDE5'},
 official:{name:'清楚招生',desc:'以資訊易讀為優先，專業可信、整齊分區、清楚的標題與報名資訊層級',main:'#466EA4',accent:'#E9F0F7'},
 minimal:{name:'極簡留白',desc:'簡約現代、充分留白、低裝飾密度，讓主題與關鍵資訊成為視覺焦點',main:'#8D7562',accent:'#F2ECE4'},
 vibrant:{name:'活潑創意',desc:'明亮有活力、圓潤幾何圖形、清楚對比，兼顧親切感與閱讀性',main:'#E38762',accent:'#FFF1D7'}
};
export const layouts={classic:{name:'上標題・下資訊',text:'上方約25%為標題區，中間約45%為主視覺，下方約30%為課程資訊區'},split:{name:'左文字・右主圖',text:'左側約55%放置標題與課程資訊，右側約45%安排主視覺，兩側保持安全間距'},frame:{name:'中央留白・周圍裝飾',text:'中央約70%為乾淨的標題與資訊空間，主視覺和裝飾安排在四周邊緣，避免侵入中央文字區'}};
export const fields=[['title','課程／活動名稱'],['subtitle','副標題'],['code','課程代碼'],['date','日期與時間'],['location','上課／活動地點'],['fee','費用與補助'],['teacher','講師'],['phone','聯絡電話'],['organizer','主辦單位'],['signup','報名方式'],['details','其他文案']];
export const defaults={mode:'background',purpose:'課程招生',size:'A4',orientation:'portrait',style:'elegant',main:'#A18ABC',accent:'#F3EAF3',decoration:'少量',layout:'classic',visual:'凝膠美甲作品與自然手部特寫',logo:true,qr:false,title:'',subtitle:'',code:'',date:'',location:'',fee:'',teacher:'',phone:'',organizer:'',signup:'',details:'',changes:'',preserve:'原有配色、背景、裝飾與未指定修改的文字',extra:''};
export function clean(raw){const d={...defaults};for(const k in defaults){if(typeof raw?.[k]===typeof defaults[k])d[k]=typeof raw[k]==='string'?raw[k].slice(0,10000):raw[k];}if(!['background','full','edit'].includes(d.mode))d.mode=defaults.mode;if(!styles[d.style])d.style=defaults.style;if(!layouts[d.layout])d.layout=defaults.layout;if(!['A4','A3','A1','square','story'].includes(d.size))d.size='A4';if(!['portrait','landscape'].includes(d.orientation))d.orientation='portrait';for(const k of ['main','accent'])if(!/^#[0-9a-f]{6}$/i.test(d[k]))d[k]=defaults[k];return d;}
export function sizeLabel(d){if(d.size==='square')return '社群正方形，1:1比例';if(d.size==='story')return '限時動態，直式9:16比例';const mm={A4:'210 × 297',A3:'297 × 420',A1:'594 × 841'};return `${d.size} ${d.orientation==='portrait'?'直式，寬高比約1:1.414':'橫式，寬高比約1.414:1'}（目標紙張尺寸 ${mm[d.size]} mm）`;}
export function generate(d){const values=fields.filter(([k])=>d[k].trim());if(d.mode==='edit')return ['請以我另外附上的原始海報為基礎進行局部修改。','【要修改的內容】',d.changes.trim()||'（請填寫具體修改項目）',...(values.length?['【修改時需使用的正確文案】',...values.map(([k,n])=>`${n}：${d[k].trim()}`)]:[]),'【必須保留】',d.preserve.trim()||'保留所有未明確要求修改的部分。','保持原圖比例與整體構圖。新填寫的文案僅用於上方明確指定的修改項目，不自動替換其他區域。不得自行新增資訊。',...(d.extra.trim()?['【其他要求】',d.extra.trim()]:[])].join('\n');
const bg=d.mode==='background';return [`請設計一張用於「${d.purpose}」的${bg?'海報底圖':'完整海報'}。`,...(d.title.trim()?[`主題：${d.title.trim()}${bg?'（僅供理解主題，不要把這些文字畫入底圖）':''}`]:[]),'', '【尺寸與構圖】',sizeLabel(d)+'。',layouts[d.layout].text+'。','重要元素與四周保留安全距離，避免裁切。','', '【視覺方向】',`${styles[d.style].name}：${styles[d.style].desc}。`,`主色 ${d.main}，輔色 ${d.accent}。裝飾密度：${d.decoration}。`,...(d.visual.trim()?[`主視覺：${d.visual.trim()}。`]:[]),'',bg?'【文字留白規則】':'【必須呈現的繁體中文文案】',...(bg?['只生成背景與圖像，不生成任何文字、字母、數字、假文字或浮水印。標題區與資訊區保持乾淨，不繪製提示標籤、虛線或佔位框。',`資訊區需預留約 ${Math.max(3,values.filter(([k])=>!['title','subtitle'].includes(k)).length)} 組資訊的排版空間。`]:values.length?values.map(([k,n])=>`${n}：${d[k].trim()}`):['（尚未填寫文案，請先補上標題與需要呈現的內容）']),...(bg?[]:['以上文案逐字呈現，使用繁體中文，保留日期、代碼、金額與電話的原始格式；不要把欄位名稱當成海報文案，除非閱讀上有需要。空白欄位不新增資訊。','標題最醒目，副標題次之，資訊區清楚易讀，文字不得超出範圍。']),...(d.logo?['右下角預留 Logo 空間，不自行生成或仿造 Logo。']:[]),...(d.qr?['下方預留乾淨的 QR code 空間，不生成假的 QR code，之後會另外加入。']:[]),...(d.extra.trim()?['','【其他要求】',d.extra.trim()]:[])].join('\n');}
