import test from 'node:test';
import assert from 'node:assert/strict';
import {defaults,clean,generate,sizeLabel,styles,layouts} from '../engine.mjs';
test('background omits exact poster copy and protects placeholders',()=>{const p=generate({...defaults,title:'美甲課程',phone:'02-8765-4321',fee:'限定費用XYZ',qr:true});assert.ok(p.includes('不生成任何文字'));assert.ok(!p.includes('02-8765-4321'));assert.ok(!p.includes('限定費用XYZ'));assert.ok(p.includes('不生成假的 QR code'));});
test('full poster preserves exact Traditional Chinese copy and punctuation',()=>{const p=generate({...defaults,mode:'full',title:'檢定衝刺班',date:'115/11/15 09:00–16:00',code:'N-001',fee:'3,000 元'});assert.ok(p.includes('日期與時間：115/11/15 09:00–16:00'));assert.ok(p.includes('課程代碼：N-001'));assert.ok(p.includes('費用與補助：3,000 元'));assert.ok(!p.includes('聯絡電話：'));});
test('edit ignores unrelated new style, size and layout',()=>{const p=generate({...defaults,mode:'edit',changes:'移除左上角 TNL',preserve:'背景與其他文字',layout:'split',style:'salon',size:'A1'});assert.ok(p.includes('移除左上角 TNL'));assert.ok(p.includes('背景與其他文字'));assert.ok(p.includes('原始海報'));assert.ok(!p.includes('55%'));assert.ok(!p.includes('沙龍'));assert.ok(!p.includes('A1'));});
test('every size and direction produces coherent aspect',()=>{assert.ok(sizeLabel({...defaults,size:'square',orientation:'landscape'}).includes('1:1'));assert.ok(sizeLabel({...defaults,size:'story',orientation:'landscape'}).includes('直式9:16'));assert.ok(sizeLabel({...defaults,orientation:'landscape'}).includes('1.414:1'));});
test('import sanitizes invalid enums, colors, oversized strings and types',()=>{const d=clean({mode:'bogus',style:'no',layout:'bad',size:'size',orientation:'xx',main:'url(x)',logo:'yes',title:'X'.repeat(20000)});assert.equal(d.mode,defaults.mode);assert.equal(d.main,defaults.main);assert.equal(d.logo,true);assert.equal(d.title.length,10000);assert.ok(styles[d.style]);assert.ok(layouts[d.layout]);});
test('all mode style layout combinations generate without undefined fields',()=>{for(const mode of ['full','background','edit'])for(const style of Object.keys(styles))for(const layout of Object.keys(layouts)){const p=generate({...defaults,mode,style,layout});assert.ok(!p.includes('undefined'));assert.ok(p.length>50);}});
